name: validate

on:
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir:
          - "."
          - "modules/vpc"
          - "modules/runner"
          - "examples/complete"
          - "examples/minimal"
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"
          terraform_wrapper: false

      - name: terraform fmt
        if: matrix.dir == '.'
        run: terraform fmt -check -recursive -diff

      - name: terraform init
        working-directory: ${{ matrix.dir }}
        run: terraform init -backend=false -input=false

      - name: terraform validate
        working-directory: ${{ matrix.dir }}
        run: terraform validate
